Progressive Writing (PW) Activities Setup - Sprint I
lablueprint/write-girl pull request #2
Opened 2023-12-05 06:33 UTC by ehng359

## Server-side Changes
* Created new model for PW Activities to be stored in the MongoDB.
* Setup basic routing for generic PW GET/POST requests to database (retrieval of all data + creating new activities).
* Created `getAllActivities`, `getActivityGenre`, `createActivity` requests to serve endpoint calls with GET/POST.

## Front-end Changes
* Setup front-end logic for 10 Doors activity and provided filtering based on selected genre.
* Added logic to manually populate activities to display onto the page regardless of genre.
* Setup logic capability to add activity directly to MongoDB database.

Initial activity page:
![Simulator Screenshot - iPhone 14 Pro - 2023-12-04 at 22 12 17](https://github.com/lablueprint/write-girl/assets/94334288/042c7635-3415-4794-97e0-4cadf809669f)

Filtering for particular genre:
![Simulator Screenshot - iPhone 14 Pro - 2023-12-04 at 22 12 23](https://github.com/lablueprint/write-girl/assets/94334288/53fa758d-389f-4ad2-a0e5-824ede3a140c)

2024-01-09 06:29 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +  const selectActivityGenre = async (name) => {
Slightly tweak filter logic based on lofi flow!
<img width="765" alt="Screenshot 2024-01-08 at 10 20 05 PM" src="https://github.com/lablueprint/write-girl/assets/69726427/25b6145c-f80b-468b-9d78-b1950c0337f4">

2024-01-12 04:24 UTC, cdebbaruah approved these changes
Great job!! The best doors ever

2024-01-23 04:32 UTC, ehng359 commented
PW Writing (PW) Activities Part 2
* Added new lo-fi design to the flow of the PWAs
* Doors now progress through steps of each instruction with a next and back capability to navigate through the activity
* Progress bar integrated to indicate how far along the current activity is.

https://github.com/lablueprint/write-girl/assets/94334288/5e4cc229-b11e-4242-a311-153d78d4f112

2024-01-30 01:15 UTC, cdebbaruah requested changes
Great job! Just a few syntax changes like limiting inline styles and adding keys to resolve the console warnings and this PR's good to go. I loved the documentation and the css is flawless!!

2024-01-30 01:15 UTC, cdebbaruah commented on server/controllers/progressiveWritingController.js
> +
We can remove this function since we're filtering on the frontend now!
```
const getActivityGenre = async (req, res) => {
  try {
    const data = await Activity.find({ genre: req.genre });
    console.log(data);
    res.send(data);
  } catch (err) {
    console.error(err);
    res.status(500).send(err);
  }
};
```

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +                style={[styles.banner, { borderRadius: 10 }]}
Let's add some kind of key here to resolve the console warnings! Considering something like:
`key={activity.activity[0]}`

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +                <TouchableOpacity
Let's add another key!
`key={label}`

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +          return (<View />);
Let's make this:
`return (<View key={activity} />);`

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +const instrDim = window.height * 0.45;
Unused const
~~const instrDim = window.height * 0.45;~~

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +  };
Since users won't be adding new activities themselves in-app, we can remove this `/createActivity` axios call!

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +    // console.log(filteredList);
~~// console.log(filteredList);~~

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +              backgroundColor: '#fff',
Try avoiding inline styling when possible! React Native's StyleSheet.create (like your `styles.banner`) caches styles. But if you declare the styles as inline then during every render your styles are sent over the bridge (which can lessen performance)!

2024-01-30 01:15 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/ProgressiveWriting.jsx
> +              {/* <Button title="Create Activity" onPress={() =>
Remove extra comments

2024-01-30 05:19 UTC, ehng359 reviewed
Resolved issues with regards to keys and unnecessary routes.

2024-01-30 05:20 UTC, cdebbaruah approved these changes

2024-01-30 05:21 UTC, merged