Triple flip history
lablueprint/write-girl pull request #26
Opened 2024-04-12 05:59 UTC by cherylwu834

Implement full stack for the Triple Flip History with controller functions and front-end styling/animation.

### Component Overview

- Name of Component: `History Screen`
- Functionality:
    - This displays all of the previously seen Triple Flip card sets that are revealed to the user.
- Where is it used:
    - The Triple Flip History Screen can be navigated to from the main Triple Flip screen.
- Sub Components or Parent Components
    - `TripleFlipHistoryCard` manage the display of each set of triple flip in the history. It manage the expanding of the cards, and displays the date along with the three topics.

### Props

- Important variables that are passed into this component:
    - `navigation` is passed so we can navigate to other pages.

### Methods

- `getHistory` retrieves the history for a given user from the database pertaining to their recently viewed history.
- `getId` retrieves the userId belonging to the current user of the session, through Redux’s Secure Store, in order to retrieve user-specific data.

### Bugs / Todos:

- Make use of secure store so we can actually retrieve the correct user-identifier for use in the application.

## Screen Recording

https://github.com/lablueprint/write-girl/assets/124432604/b425518b-6377-4f42-b1d3-7c7858adadfc

2024-04-26 04:56 UTC, cdebbaruah requested changes
The triple flips cards & history screen look amazing!! I noticed some minor nav errors that probably just resulted from merging with main. But overall you guys did great work! I'm so impressed 💯

2024-04-26 04:56 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/TripleFlipScreen.jsx
> +  View, Text, StyleSheet, Dimensions, Button, TouchableOpacity,
We can remove the extraneous imports! (`Button`, `useAnimatedStyle`, `useSharedValue`, `withDelay`, `withSpring`)

2024-04-26 04:56 UTC, cdebbaruah commented on mobile/Screens/WritingActivities/TripleFlipScreen.jsx
> +  [2 * cardHeight - OFFSET, cardHeight - OFFSET, 0 - OFFSET, -cardHeight + 10 - OFFSET, -2 * cardHeight + 20 - OFFSET],
Limit each line to 100 chars when possible to avoid those `eslint` warnings

2024-04-26 04:56 UTC, cdebbaruah commented on mobile/Navigation/AppNavigation.jsx
> +};
I think the `createtabOptions` and `middleTabOptions` are duplicated  in AppNav

2024-04-26 04:56 UTC, cdebbaruah commented on mobile/Navigation/AppNavigation.jsx
> +function MainAppScreen() {
Let's keep this function as `HomeStackScreen` since we call `HomeStackScreen` in our export default function. Alternatively, change the component name to `MainAppScreen` in the default function.

2024-04-26 04:56 UTC, cdebbaruah commented on mobile/Navigation/AppNavigation.jsx
>        screenOptions={{
Replace the center `HomeScreen` component with your new HomeScreenStack

2024-04-26 04:56 UTC, cdebbaruah commented on mobile/Components/TripleFlipCard.jsx
> +  View, StyleSheet, Text, Image,
~~import View~~

2024-04-26 04:56 UTC, cdebbaruah commented on mobile/Components/TripleFlipCard.jsx
> +  image: PropTypes.string.isRequired,
We can change this to `PropTypes.number.isRequired` since `require('../../assets/logo.png')` actually returns a number not a string

2024-05-03 06:11 UTC, cherylwu834 reviewed
Lgtm

2024-05-03 06:12 UTC, ehng359 approved these changes
LGTM too. @cdebbaruah let us know when we can merge this in, I think it is still indicating merging is blocked.

2024-05-03 06:13 UTC, ehng359 approved these changes

2024-05-07 04:52 UTC, cdebbaruah approved these changes
YAYY LGTM!!!!

2024-05-07 04:59 UTC, merged